In [1]:
#Q1. Difference in the data type of variables list_ and array_list

import numpy as np


list_ = [ '1' , '2' , '3' , '4' , '5' ]
array_list = np.array(object = list_)

print(f'Data type of list_ : {type(list_)}')        # Printing the data type of 'list_'
print(f'Data type of array_list : {type(array_list)}')        # Printing the data type of 'array_list'

Data type of list_ : <class 'list'>
Data type of array_list : <class 'numpy.ndarray'>


There is a difference in the data types of 'list_' and 'array_list' where 'list_' has a data type of class 'list' while the data type of 'array_list' is of class 'numpy.ndarray'.

In [2]:
#Q2. Code to print each and every element of both the variables list_ and array_list

# Printing data type of each and every element of 'list_'

print('Data type of each and every element of list_ :- \n')
for element in list_:
    print(f'Data type of {element} is {type(element)}.')

# Printing data type of each and every element of 'array_list'

print('\nData type of each and every element of array_list :- \n')
for element in array_list:
    print(f'Data type of {element} is {type(element)}.')

Data type of each and every element of list_ :- 

Data type of 1 is <class 'str'>.
Data type of 2 is <class 'str'>.
Data type of 3 is <class 'str'>.
Data type of 4 is <class 'str'>.
Data type of 5 is <class 'str'>.

Data type of each and every element of array_list :- 

Data type of 1 is <class 'numpy.str_'>.
Data type of 2 is <class 'numpy.str_'>.
Data type of 3 is <class 'numpy.str_'>.
Data type of 4 is <class 'numpy.str_'>.
Data type of 5 is <class 'numpy.str_'>.


In [3]:
#Q3. Difference in the data type of variables list_ and array_list after change

array_list = np.array(object = list_, dtype = int)

# Printing data type of each and every element of 'list_'

print('Data type of each and every element of list_ :- \n')
for element in list_:
    print(f'Data type of {element} is {type(element)}.')

# Printing data type of each and every element of 'array_list'

print('\nData type of each and every element of array_list :- \n')
for element in array_list:
    print(f'Data type of {element} is {type(element)}.')

Data type of each and every element of list_ :- 

Data type of 1 is <class 'str'>.
Data type of 2 is <class 'str'>.
Data type of 3 is <class 'str'>.
Data type of 4 is <class 'str'>.
Data type of 5 is <class 'str'>.

Data type of each and every element of array_list :- 

Data type of 1 is <class 'numpy.int64'>.
Data type of 2 is <class 'numpy.int64'>.
Data type of 3 is <class 'numpy.int64'>.
Data type of 4 is <class 'numpy.int64'>.
Data type of 5 is <class 'numpy.int64'>.


There will be a difference in the data type of the elements present in both the variables, 'list_' and 'array_list' where each element of 'list_' has a data type of class 'str' while each element of 'array_list' has a data type of class 'numpy.int64'.

In [4]:
#Q4. Code to find the shape and size of the variable, 'num_array'

import numpy as np


num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

# (i) Finding the shape of the variable, num_array

print(f'Shape of the variable, num_array is {num_array.shape}.')

# (ii) Finding the size of the variable, num_array

print(f'\nSize of the variable, num_array is {num_array.size}.')

Shape of the variable, num_array is (2, 3).

Size of the variable, num_array is 6.


In [5]:
#Q5. Code to create numpy array of 3*3 matrix containing zeros only

import numpy


zero_array = numpy.zeros((3, 3))        # Creating the numpy array of 3*3 matrix containing zeros only

print(f'The numpy array of 3*3 matrix containing zeros only is as follows :-\n\n{zero_array}')        # Printing the numpy array of 3*3 matrix containing zeros only

The numpy array of 3*3 matrix containing zeros only is as follows :-

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [6]:
#Q6. Code to create identity matrix of shape (5,5)

import numpy


zero_array = numpy.eye(5)        # Creating the identity matrix of shape (5,5)

print(f'The identity matrix of shape (5,5) is as follows :-\n\n{zero_array}')        # Printing the identity matrix of shape (5,5)

The identity matrix of shape (5,5) is as follows :-

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
